FROM golang:1.21 AS builder

WORKDIR /src/
COPY . .

RUN go build -o /app/webapi ./cmd/webapi


FROM debian:bookworm

EXPOSE 3000

WORKDIR /app/
COPY --from=builder /app/webapi ./

RUN mkdir /data
ENV DB_PATH=/data/wasatext.db
VOLUME ["/data"]

CMD ["/app/webapi"]
